/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementsystem;



/**
 *
 * @author Savita
 */
public class HomeMenu extends javax.swing.JFrame {

    /**
     * Creates new form HomeMenu
     */
    public HomeMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        Bill = new javax.swing.JRadioButton();
        View = new javax.swing.JRadioButton();
        Room = new javax.swing.JRadioButton();
        Logo = new javax.swing.JRadioButton();
        Exit = new javax.swing.JRadioButton();
        View1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1360, 780));
        getContentPane().setLayout(null);

        Bill.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        Bill.setText("Generate Bill");
        Bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillActionPerformed(evt);
            }
        });
        getContentPane().add(Bill);
        Bill.setBounds(80, 200, 170, 37);

        View.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        View.setText("View Visitor Details");
        getContentPane().add(View);
        View.setBounds(80, 250, 225, 37);

        Room.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        Room.setText("Room ");
        getContentPane().add(Room);
        Room.setBounds(80, 150, 120, 37);

        Logo.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        Logo.setText("Logout");
        getContentPane().add(Logo);
        Logo.setBounds(80, 350, 130, 37);

        Exit.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        Exit.setText("Exit");
        getContentPane().add(Exit);
        Exit.setBounds(80, 400, 130, 37);

        View1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        View1.setText("View Room Details");
        getContentPane().add(View1);
        View1.setBounds(80, 300, 210, 37);

        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(680, 530, 160, 40);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setText("Mirates Hotel Company");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 30, 480, 55);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagementsystem/Vastu-for-room-size.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1366, 768));
        jLabel2.setMinimumSize(new java.awt.Dimension(1366, 768));
        jLabel2.setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -22, 1366, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: if(RProcessing.isSelected())
        if(Room.isSelected())
        {
            RoomProcessing RP = new RoomProcessing();
            RP.setVisible(true);
            this.setVisible(false);
        }
       
        else if(Bill.isSelected())
        {
            GenerateBill GB = new GenerateBill();
            GB.setVisible(true);
            this.setVisible(false);
        }
         else if(View.isSelected())
        {
            ViewVisitors Vr = new ViewVisitors();
            Vr.setVisible(true);
            this.setVisible(false);
        }
           else if(View1.isSelected())
        {
            ViewRoom Vr1 = new ViewRoom();
            Vr1.setVisible(true);
            this.setVisible(false);
        }
         else if(Logo.isSelected())
        {
             Login Log = new Login();
             Log.setVisible(true);
             this.setVisible(false);
        }
        else if(Exit.isSelected())
        {
            this.dispose();
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BillActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
                    
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Bill;
    private javax.swing.JRadioButton Exit;
    private javax.swing.JRadioButton Logo;
    private javax.swing.JRadioButton Room;
    private javax.swing.JRadioButton View;
    private javax.swing.JRadioButton View1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    // End of variables declaration//GEN-END:variables
}
